# ~/.config/hypr/hyprlauncher.conf

# ── General UI settings ──
general {
    grab_focus = true
}

ui {
    # Adjust this to change the size of the launcher box
    window_size = 400 260
}

# ── Finder settings ──
finders {
    # This is the exact prefix hyprlauncher will put in front of the application's Exec command.
    desktop_launch_prefix = uwsm-app
    
    # Enable searching for desktop apps natively
    default_finder = desktop
}
